name: Deploy MkDocs site

on:
  push:
    branches: [main]    # Deploy on push to main
  pull_request:
    branches: [main]    # Build/check (not deploy) on pull requests to main

permissions:
  contents: write       # GitHub Pages and artifact upload require content write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Build site
        run: mkdocs build
      # Optional: upload build artifact for preview on PRs
      - name: Upload artifact (PR only)
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: site/

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force      # This deploys your site to the gh-pages branch
